// Code generated by mockery v2.53.5. DO NOT EDIT.

package converter

import (
	model "github.com/bauersimon/grnkdb/model"
	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function with given fields: videos
func (_m *MockInterface) Convert(videos []*model.Video) ([]*model.Game, error) {
	ret := _m.Called(videos)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 []*model.Game
	var r1 error
	if rf, ok := ret.Get(0).(func([]*model.Video) ([]*model.Game, error)); ok {
		return rf(videos)
	}
	if rf, ok := ret.Get(0).(func([]*model.Video) []*model.Game); ok {
		r0 = rf(videos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Game)
		}
	}

	if rf, ok := ret.Get(1).(func([]*model.Video) error); ok {
		r1 = rf(videos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterface_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type MockInterface_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - videos []*model.Video
func (_e *MockInterface_Expecter) Convert(videos interface{}) *MockInterface_Convert_Call {
	return &MockInterface_Convert_Call{Call: _e.mock.On("Convert", videos)}
}

func (_c *MockInterface_Convert_Call) Run(run func(videos []*model.Video)) *MockInterface_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*model.Video))
	})
	return _c
}

func (_c *MockInterface_Convert_Call) Return(_a0 []*model.Game, _a1 error) *MockInterface_Convert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterface_Convert_Call) RunAndReturn(run func([]*model.Video) ([]*model.Game, error)) *MockInterface_Convert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
