// Code generated by mockery v2.53.5. DO NOT EDIT.

package scraper

import (
	model "github.com/bauersimon/grnkdb/model"
	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Videos provides a mock function with given fields: channelID
func (_m *MockInterface) Videos(channelID string) ([]*model.Video, error) {
	ret := _m.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for Videos")
	}

	var r0 []*model.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.Video, error)); ok {
		return rf(channelID)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.Video); ok {
		r0 = rf(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterface_Videos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Videos'
type MockInterface_Videos_Call struct {
	*mock.Call
}

// Videos is a helper method to define mock.On call
//   - channelID string
func (_e *MockInterface_Expecter) Videos(channelID interface{}) *MockInterface_Videos_Call {
	return &MockInterface_Videos_Call{Call: _e.mock.On("Videos", channelID)}
}

func (_c *MockInterface_Videos_Call) Run(run func(channelID string)) *MockInterface_Videos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockInterface_Videos_Call) Return(_a0 []*model.Video, _a1 error) *MockInterface_Videos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterface_Videos_Call) RunAndReturn(run func(string) ([]*model.Video, error)) *MockInterface_Videos_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
